<a href="https://colab.research.google.com/github/adenike92/Projects/blob/main/Copy_of_logistic_regression_By_Performance_Rating.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Read CSV file
df = pd.read_csv('/content/california-surgeon-performance-ratings-for-cabg-2017-2018.csv')
df.head()


In [ ]:
# List of columns to drop
columns_to_drop = ['Year','Surgeon ID', 'Statewide All CABG Cases', 'Statewide Isolated CABG Cases',
                   'Statewide Isolated CABG Deaths','Statewide Observed Mortality Rate(%)'
                    ]

# Drop the specified columns
df = df.drop(columns=columns_to_drop)

# Print the DataFrame to verify the changes
print(df)

In [ ]:
#chech for missing date, outliers
print(df.isnull().sum())

 Surgeon Total CABG Cases                                      0
 Surgeon Total Isolated CABG Cases                             0
 Surgeon Total Isolated CABG Deaths                            0
Overall Surgeon Operative Mortality  Risk Adjusted Rate (%)    0
Overall Surgeon LCL                                            0
Overall Surgeon UCL                                            0
Overall Performance Rating                                     0
dtype: int64


In [ ]:
# Remove duplicate rows from the DataFrame
df = df.drop_duplicates()
print(df.isnull().sum())



 Surgeon Total CABG Cases                                      0
 Surgeon Total Isolated CABG Cases                             0
 Surgeon Total Isolated CABG Deaths                            0
Overall Surgeon Operative Mortality  Risk Adjusted Rate (%)    0
Overall Surgeon LCL                                            0
Overall Surgeon UCL                                            0
Overall Performance Rating                                     0
dtype: int64


In [ ]:
# Check data type.
data_types = df.dtypes
print(data_types)

 Surgeon Total CABG Cases                                        int64
 Surgeon Total Isolated CABG Cases                               int64
 Surgeon Total Isolated CABG Deaths                              int64
Overall Surgeon Operative Mortality  Risk Adjusted Rate (%)    float64
Overall Surgeon LCL                                            float64
Overall Surgeon UCL                                            float64
Overall Performance Rating                                      object
dtype: object


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer

In [ ]:
# Assuming 'performance_rating' is the target variable
# and other columns are features
X = df.drop('Overall Performance Rating', axis=1)  # Features
y = df['Overall Performance Rating']  # Target

In [ ]:
# Standardize features by removing the mean and scaling to unit variance
scaler = MinMaxScaler()
scaler.fit(X)
X_scaled = scaler.transform(X)

In [ ]:
#label encoding the target variable using labelencoder
Label_encoder = LabelEncoder()
y = Label_encoder.fit_transform(y)
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 1]


In [ ]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

In [ ]:
# Initialize logistic regression model with regularization (L2) and cross-entropy loss
# You can adjust the regularization strength 'C' for better performance
model = LogisticRegression(penalty='l2', solver='lbfgs', max_iter=1000, C=0.01, multi_class='auto')

In [ ]:
# Train the model
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

#computing accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy*100))

# Model evaluation
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Accuracy: 96.39%
Confusion Matrix:
[[80  0]
 [ 3  0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.96      1.00      0.98        80
           2       0.00      0.00      0.00         3

    accuracy                           0.96        83
   macro avg       0.48      0.50      0.49        83
weighted avg       0.93      0.96      0.95        83



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Applying cross validation tecchinque to handle likely overfitting issues.

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score
from sklearn.metrics import make_scorer, precision_score, recall_score, f1_score
# Initialize logistic regression model
model = LogisticRegression()

# Perform cross-validation with 5 folds
# You can adjust the number of folds (cv parameter) as needed
# Here, we use accuracy as the scoring metric
# You can change the scoring metric as needed
scores = cross_val_score(model, X_scaled, y, cv=5, scoring='accuracy')

# Print cross-validation scores
print("Cross-Validation Scores:")
print(scores)

# Calculate and print the mean and standard deviation of the cross-validation scores
print(f"Mean Accuracy: {scores.mean():.2f}")
print(f"Standard Deviation of Accuracy: {scores.std():.2f}")




Cross-Validation Scores:
[0.98181818 0.98181818 0.98181818 0.98181818 0.96363636]
Mean Accuracy: 0.98
Standard Deviation of Accuracy: 0.01


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(


In [ ]:

y_pred_cv = cross_val_predict(model, X_scaled, y, cv=5)

# Calculate precision, recall, and F1-score
precision = precision_score(y, y_pred_cv, average='weighted')
recall = recall_score(y, y_pred_cv, average='weighted')
f1 = f1_score(y, y_pred_cv, average='weighted')

# Print precision, recall, and F1-score
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-score: {f1:.2f}")



Precision: 0.96
Recall: 0.98
F1-score: 0.97


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
# Calculate and print confusion matrix
conf_matrix = confusion_matrix(y, y_pred_cv)
print("Confusion Matrix:")
print(conf_matrix)

print("\nClassification Report:")
print(classification_report(y, y_pred_cv))


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Confusion Matrix:
[[269   0   0]
 [  2   0   0]
 [  4   0   0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       269
           1       0.00      0.00      0.00         2
           2       0.00      0.00      0.00         4

    accuracy                           0.98       275
   macro avg       0.33      0.33      0.33       275
weighted avg       0.96      0.98      0.97       275



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


# Standardize features by removing the mean and scaling to unit variance
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Initialize SVM model
model = SVC(kernel='rbf', random_state=42)  # Using RBF kernel as an example, you can also try linear, polynomial, etc.

# Train the model
model.fit(X_train_scaled, y_train)

# Predictions
y_pred = model.predict(X_test_scaled)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.9636363636363636

Confusion Matrix:
[[53  0]
 [ 2  0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.96      1.00      0.98        53
           2       0.00      0.00      0.00         2

    accuracy                           0.96        55
   macro avg       0.48      0.50      0.49        55
weighted avg       0.93      0.96      0.95        55



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
# Import necessary libraries
import tensorflow
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Build neural network model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(64, activation='relu'),
    Dense(3, activation='softmax')  # 3 output classes corresponding to performance ratings
])

# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',  # Use sparse categorical cross-entropy for integer-encoded target
              metrics=['accuracy'])

# Train the model
model.fit(X_train_scaled, y_train, epochs=20, batch_size=32, verbose=1)

# Evaluate the model on test data
test_loss, test_accuracy = model.evaluate(X_test_scaled, y_test, verbose=0)
print(f"Test Accuracy: {test_accuracy:.2f}")

# Make predictions
y_pred = np.argmax(model.predict(X_test_scaled), axis=-1)

# Convert predictions back to original labels (if needed)
#y_pred_label = Label_encoder.inverse_transform(y_pred)

# Print classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Epoch 1/20
7/7 [==============================] - 1s 5ms/step - loss: 1.0149 - accuracy: 0.6455
Epoch 2/20
7/7 [==============================] - 0s 3ms/step - loss: 0.7671 - accuracy: 0.9818
Epoch 3/20
7/7 [==============================] - 0s 3ms/step - loss: 0.5755 - accuracy: 0.9818
Epoch 4/20
7/7 [==============================] - 0s 3ms/step - loss: 0.4263 - accuracy: 0.9818
Epoch 5/20
7/7 [==============================] - 0s 3ms/step - loss: 0.3171 - accuracy: 0.9818
Epoch 6/20
7/7 [==============================] - 0s 4ms/step - loss: 0.2431 - accuracy: 0.9818
Epoch 7/20
7/7 [==============================] - 0s 4ms/step - loss: 0.1937 - accuracy: 0.9818
Epoch 8/20
7/7 [==============================] - 0s 3ms/step - loss: 0.1690 - accuracy: 0.9818
Epoch 9/20
7/7 [==============================] - 0s 3ms/step - loss: 0.1536 - accuracy: 0.9818
Epoch 10/20
7/7 [==============================] - 0s 3ms/step - loss: 0.1421 - accuracy: 0.9818
Epoch 11/20
7/7 [======================

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
